# Generated by Django 5.1.5 on 2025-02-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='توضیحات مجموعه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'درباره',
                'verbose_name_plural': 'درباره ما',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256, verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پرسش',
                'verbose_name_plural': 'پرسش و پاسخ',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('location', models.URLField(max_length=1024, verbose_name='لینک گوگل مپ')),
                ('phone', models.CharField(max_length=16, verbose_name='شماره')),
                ('instagram', models.CharField(max_length=48, verbose_name='اینستاگرام')),
                ('whatsapp', models.URLField(max_length=256, verbose_name='لینک واتس آپ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'راه ارتباطی',
                'verbose_name_plural': 'راه ارتباطی',
            },
        ),
        migrations.CreateModel(
            name='FirstContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='نام سایت')),
                ('photo', models.ImageField(upload_to='logo/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نام و لوگو',
                'verbose_name_plural': 'نام و لوگو',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='نام عکس')),
                ('photo', models.ImageField(upload_to='gallery/', verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ما',
            },
        ),
        migrations.CreateModel(
            name='TextAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=156, verbose_name='نام عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'متن روان',
                'verbose_name_plural': 'متن روان',
            },
        ),
    ]
